from dotenv import load_dotenv
import os

load_dotenv()

QIANFAN_ACCESS_KEY = os.getenv('QIANFAN_ACCESS_KEY')
QIANFAN_SECRET_KEY = os.getenv('QIANFAN_SECRET_KEY')

QIANFAN_IMAGE_ACCESS_KEY = os.getenv('QIANFAN_IMAGE_ACCESS_KEY')
QIANFAN_IMAGE_SECRET_KEY = os.getenv('QIANFAN_IMAGE_SECRET_KEY')
